# Generated by Django 5.0.7 on 2024-12-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_simsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='simsconfig',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='configs/images/'),
        ),
    ]
