# Generated by Django 5.0.7 on 2024-12-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_simsconfig_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.branch'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.school'),
        ),
        migrations.AddField(
            model_name='loginactivitylog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.branch'),
        ),
        migrations.AddField(
            model_name='loginactivitylog',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.school'),
        ),
    ]
