# Generated by Django 5.0.7 on 2024-12-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_classroom_classroommessage_hostelleave_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='file_name',
        ),
    ]
