# Generated by Django 5.0.7 on 2024-12-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_remove_teacher_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='student_child', to='api_v1.student'),
        ),
    ]
