# Generated by Django 5.0.7 on 2024-12-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_userdocument_branch_userdocument_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='component_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appitem',
            name='component_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
