# Generated by Django 5.0.7 on 2024-12-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_app_component_key_appitem_component_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='school',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='status',
        ),
    ]
