# Generated by Django 5.0.7 on 2024-12-22 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0014_classroom_active_classroom_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.AddField(
            model_name='classroom',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
