# Generated by Django 5.0.7 on 2024-12-25 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0015_remove_classroom_students_classroom_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgallery',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='store_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.branch')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.school')),
            ],
        ),
    ]
