# Generated by Django 5.0.7 on 2024-12-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0017_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_form',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
