# Generated by Django 5.0.7 on 2025-01-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0018_school_short_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
