# Generated by Django 5.0.7 on 2025-01-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0019_schoolclass_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='date',
        ),
        migrations.AddField(
            model_name='club',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.teacher'),
        ),
    ]
