# Generated by Django 5.0.7 on 2025-01-05 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0022_studentfee_academic_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Meeting Link')),
                ('code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Code')),
                ('time_duration', models.DurationField(verbose_name='Time Duration')),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.branch')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingcreator', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.schoolclass')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.section')),
            ],
        ),
    ]
