# Generated by Django 5.0.7 on 2025-01-05 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0023_earning_date_expense_date_noticeboard_date_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
