# Generated by Django 5.0.7 on 2025-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0025_meeting_active_meeting_created_at_meeting_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
