# Generated by Django 5.0.7 on 2025-01-06 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0026_meeting_start_date_meeting_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsupport',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.branch'),
        ),
        migrations.AddField(
            model_name='helpsupport',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.school'),
        ),
        migrations.AddField(
            model_name='helpsupport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
