# Generated by Django 5.0.7 on 2025-01-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0029_category_coupon_cart_product_cartitems_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
