# Generated by Django 5.0.7 on 2025-01-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0035_alter_notification_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='guests',
            field=models.JSONField(default=list, verbose_name='Guest Emails'),
        ),
    ]
