# Generated by Django 5.0.7 on 2025-01-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0036_meeting_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroommessage',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api_v1.classroommessage'),
        ),
    ]
