# Generated by Django 5.0.7 on 2025-01-17 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0039_feestructure_late_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecategory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feecategory',
            name='applicable_to',
        ),
        migrations.RemoveField(
            model_name='feecategory',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='FeeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.branch')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
