# Generated by Django 5.0.7 on 2025-01-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0040_remove_feecategory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feenote',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.branch'),
        ),
        migrations.AlterField(
            model_name='feenote',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.school'),
        ),
    ]
