# Generated by Django 5.0.7 on 2025-01-18 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0041_alter_feenote_branch_alter_feenote_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.academicsession'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='due_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
