# Generated by Django 5.0.7 on 2025-01-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0042_feestructure_session_studentfee_due_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='due_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
