# Generated by Django 5.0.7 on 2025-01-20 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0045_alter_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feereceipt',
            name='receipt_date',
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feereceipt', to='api_v1.payment'),
        ),
    ]
