# Generated by Django 5.0.7 on 2025-01-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0047_accessmethod_gatepass_gatetype_useraccesspass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finger_prints',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rfid_card_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
