# Generated by Django 5.0.7 on 2025-01-29 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0048_user_finger_prints_user_rfid_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='parent',
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
