# Generated by Django 5.0.7 on 2025-01-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0049_remove_visitor_parent_visitor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
