# Generated by Django 5.0.7 on 2025-02-05 02:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0052_branch_email_school_email_alter_user_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='school',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='transport_route',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='student',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.vehicle'),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_contact',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_license',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.branch'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='route_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_incharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.school'),
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.branch')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='routes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.busroute'),
        ),
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('route_fair', models.CharField(blank=True, max_length=10)),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.branch')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='busroute',
            name='end_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_station', to='api_v1.busstation'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='start_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_station', to='api_v1.busstation'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='stop_points',
            field=models.ManyToManyField(blank=True, related_name='stop_points', to='api_v1.busstation'),
        ),
        migrations.DeleteModel(
            name='Transport_Route',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
