# Generated by Django 5.0.7 on 2025-02-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0053_remove_transport_branch_remove_transport_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine_status',
            field=models.CharField(default='off', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
