# Generated by Django 5.0.7 on 2025-02-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0055_remove_subject_teacher_remove_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstation',
            name='place_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
