# Generated by Django 5.0.7 on 2025-02-14 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0057_remove_vehicle_status_alter_vehicle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='passenger',
            field=models.ManyToManyField(blank=True, null=True, related_name='passenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_made',
            field=models.DateField(blank=True, null=True),
        ),
    ]
