# Generated by Django 5.0.7 on 2025-02-14 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0058_alter_vehicle_passenger_alter_vehicle_year_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='passenger',
            field=models.ManyToManyField(blank=True, related_name='passenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
