# Generated by Django 5.0.7 on 2025-02-14 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0059_alter_vehicle_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='api_v1.vehicle'),
        ),
        migrations.AlterField(
            model_name='busstation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busstation',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busstation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busstation',
            name='route_fair',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
